### PR TITLE
fix: locales not being included when srcDir has been changed

### LINKED ISSUE #1963: Spaces in YAML translation files with nuxt `srcDir` config
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `app`, `ssr`, `srcDir`, `modules`, `vite`, `nitro`, `googleFonts`, `i18n`, `content`, `plausible`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.4`, `@pinia/nuxt@0.4.7`, `@nuxtjs/google-fonts@3.0.0`, `nuxt-icon@0.3.3`, `@nuxtjs/i18n-edge@8.0.0-beta.10-27995650.c1d4ec9`, `@nuxt/content@2.5.2`, `@nuxtjs/plausible@0.2.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-rg81ao
https://stackblitz.com/edit/github-rg81ao-u5wrhd (without srcDir)

### Describe the bug

Updating from `8.0.0-beta.10-27985006.4ff543e` to `8.0.0-beta.10-27995650.c1d4ec9` it seems that strings with spaces are no longer accepted in YAML translation files when not wrapped into quotes:

```yaml
demoStringQuotes: 'String with spaces with quotes'
demoString: String with spaces
```

Run `npm run generate` in the [reproduction repo on StackBlitz](https://stackblitz.com/edit/github-rg81ao) to see how the build fails.

This seems to be related to the nuxt `srcDir` config. Without this everything works as expected. Compare with `npm run generate` in the [reproduction repo without srcDir](https://stackblitz.com/edit/github-rg81ao-u5wrhd).

### Additional context

_No response_

### Logs

Bildschirm­foto 2023-03-29 um 11 34 05

### PR DESCRIPTION
**Pull request by BobbieGoede**
### 🔗 Linked issue
#1963 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Resolves #1963 

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/layers.ts [hunk 1]
```diff
@@ -149,6 +149,6 @@ export const getLayerLangPaths = (nuxt: Nuxt) => {
     nuxt.options._layers
       .filter(layer => layer.config.i18n?.langDir != null)
       // @ts-ignore
-      .map(layer => pathe.resolve(layer.config.rootDir, layer.config.i18n.langDir)) as string[]
+      .map(layer => pathe.resolve(layer.config.rootDir, layer.config.srcDir, layer.config.i18n.langDir)) as string[]
```
Comment (WolfgangDrescher) [inline src/layers.ts]: Debugging this I found that `layer.config.srcDir` already has `layer.config.rootDir` included. So you should probably use:

```ts
pathe.resolve(layer.config.srcDir, layer.config.i18n.langDir)
```

But I'm not sure if I'm correct with this.

Comment (WolfgangDrescher) [reply src/layers.ts]: Oops. Messed up the copy&pase. I meant `pathe.resolve(layer.config.srcDir, layer.config.i18n.langDir)` and updated my previous comment.

**Comment by WolfgangDrescher** [comment]
Adding `srcDir` could also be relevant for `mergeLayerPages()` and maybe also other places.

File: src/layers.ts (hunk 1 above)
Comment (BobbieGoede) [reply src/layers.ts]: You're right, it looks like `srcDir` includes the absolute path, I thought it would use the configured value of `srcDir`. But as seen here `rootDir` is always part of `srcDir` on `_layers` https://github.com/nuxt/nuxt/blob/ae82d7089598bd1a4e5a8f88cd9edf7a1f12d7c7/packages/kit/src/loader/config.ts#L34

Comment (WolfgangDrescher) [reply src/layers.ts]: Ah nice catch. Thank you for checking this.

**Comment by BobbieGoede** [comment]
> Adding `srcDir` could also be relevant for `mergeLayerPages()` and maybe also other places.

That's a good point! I will test a custom `srcDir` with custom pages dir (in project and/or layer) when I have the time.
