### PR TITLE
fix: compatibility issue with Nuxt 2.15.0

### LINKED ISSUE #1063: Nuxt@2.15.0 error - Cannot read property 'options' of undefined
### Version
nuxt-i18n: 6.20.0
nuxt: 2.15.0

#### [mode](https://nuxtjs.org/guides/configuration-glossary/configuration-mode): 
 - [X] universal

### Nuxt-i18n configuration
```
i18n: {
        locales: [...],
        defaultLocale: "en",
        vueI18nLoader: true
    }
```

### What is Expected?
Not sure where the issue lies and what could have changed since the previous version of Nuxt, but the description of the issue should be self explanatory about what is failing and where.

### What is actually happening?
Error when running npm run dev for Nuxt:
image

Result of console.log(config.module.rules) above failing line;
image

hooks.js logic which is looking for vue-loader when on the screenshot above there is an absolute path not equal to but **including** vue-loader:
image

### PR DESCRIPTION
**Pull request by rchl**
Resolves #1063

### CODE REVIEW

File: src/core/hooks.js [hunk 1]
```diff
@@ -48,11 +48,11 @@ export function buildHook (moduleContainer, options) {
...
   if (options.vueI18nLoader) {
     moduleContainer.extendBuild(config => {
-      const loaders = config.module.rules.find(el => el.loader === 'vue-loader').options.loaders
-      if (loaders) {
+      const vueLoader = config.module.rules.find(el => el.loader.includes('vue-loader'))
+      if (vueLoader && vueLoader.options && vueLoader.options.loaders) {
         // vue-loader under 15.0.0
         /* istanbul ignore next */
-        loaders.i18n = '@intlify/vue-i18n-loader'
+        vueLoader.options.loaders.i18n = '@intlify/vue-i18n-loader'
```
Comment (pi0) [inline src/core/hooks.js]: It would be nice if you use `require.resolve` here to resovle `@intlify/vue-i18n-loader` on behalf of module (otherwise we depend on implicit `node_modules` structure)

Comment (rchl) [reply src/core/hooks.js]: Done.
