### PR TITLE
fix: correct root redirection with query params

### LINKED ISSUE #3733: Redirects are not properly resolved when the URL contians query params
### Environment

- Operating System: Darwin
- Node Version:     v22.16.0
- Nuxt Version:     3.17.7
- CLI Version:      3.26.2
- Nitro Version:    2.12.2
- Package Manager:  pnpm@10.13.1
- Builder:          -
- User Config:      compatibilityDate, future, devtools, telemetry, debug, runtimeConfig, app, css, postcss, tailwindcss, modules, cms, build, storefront, storefront-ui, svgo, fonts, image, experimental, i18n, opentelemetry, imports, vueuse, components, vue, devServer, ignore, routeRules, vite, hooks, nitro, optimization
- Runtime Modules:  @nuxtjs/i18n@10.0.0, @scayle/storefront-nuxt/module@8.33.2, @scayle/omnichannel-nuxt/module@4.3.2, @nuxtjs/tailwindcss@6.14.0, nuxt-svgo@4.2.4, @nuxt/fonts@0.11.4, @nuxt/image@1.10.0, @vueuse/nuxt@13.5.0, nuxt-swiper@1.2.2, @nuxt/test-utils/module@3.19.2, @nuxt/eslint@1.4.1, @scayle/eslint-auto-explicit-import@0.2.0, @scayle/nuxt-opentelemetry@0.13.10, @scayle/storefront-country-detection@2.0.0, @scayle/storefront-product-detail@1.5.0, @scayle/storefront-product-listing@2.0.1, @scayle/storefront-promotions@2.2.0, @scayle/storefront-search@0.3.0, @scayle/storefront-basket@0.3.0, @scayle/storefront-navigation@0.3.0, @scayle/nuxt-image-provider@0.3.1, @nuxtjs/storybook@8.4.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-a8x1bxda?file=i18n%2Fi18n.config.ts

### Describe the bug

I use a module that relies on the correct locale during SSR. When I set the strategy to `prefix` and open some site without prefix but with query params, the default locale is missing during SSR. 

In my case, this cause the page to crash. 

### Additional context

_No response_

### Logs

```shell

```

### PR DESCRIPTION
**Pull request by lutejka**
### 🔗 Linked issue

Resolves #3733

### 📚 Description

The redirect middleware compared `event.path` to `/` to check if the prefix is missing. However, `event.path` does include the query string. Therefore, the redirects did not work properly when there was no prefix but a query string

## Summary by CodeRabbit

* **Bug Fixes**
  * Ensured query parameters are preserved during locale and root redirects.

* **Tests**
  * Added and expanded test cases verifying query parameter retention in locale-prefixed and root redirect URLs.

### CODE REVIEW

File: src/runtime/server/plugin.ts [hunk 1]
```diff
@@ -109,19 +109,21 @@ export default defineNitroPlugin(async nitro => {
 
     let resolvedPath = undefined
     let redirectCode = 302
-    if (rootRedirect && event.path === '/') {
+    const requestURL = new URL(getRequestURL(event))
```
Comment (BobbieGoede) [inline src/runtime/server/plugin.ts]: The value returned by `getRequestURL` is already a `URL` so we should be able to use that directly.

```suggestion
    const requestURL = getRequestURL(event)
```

**Review by BobbieGoede — APPROVED** [review]
Thank you so much! 🙏  I can't believe this was not already covered by the tests 🫣
